import {Component, effect, inject, input, OnInit, output} from '@angular/core';
import {FormGroup, ReactiveFormsModule} from '@angular/forms';
import {FormlyFieldConfig, FormlyFormOptions, FormlyModule} from '@ngx-formly/core';
import moment from 'moment';
import { v4 as uuidv4 } from 'uuid';
import {AppButton} from '@shared/components/app-button/app-button';
import {KeyValue} from '@shared/interfaces/keyvalue';
import {EventManagementService} from '../event-management-service';
import {map} from 'rxjs/operators';
import {CategoryService} from '@shared/service/category.service';

@Component({
  selector: 'app-event-form',
  imports: [
    ReactiveFormsModule,
    FormlyModule,
    AppButton
  ],
  templateUrl: './event-form.html',
  styleUrl: './event-form.scss',
})
export class EventForm implements OnInit {
  data = input<{
    [key: string]: any;
  }>();
  isEdit = input<boolean>(false);
  loading = input<boolean>(false);
  onSubmit = output();

  private eventService = inject(EventManagementService);
  private categoryService = inject(CategoryService);

  constructor() {
    effect(() => {
      const model = this.data();
      this.model = {...model};
    });

    effect(() => {
      const isWildlife = this.categoryService.isWildlife();
      if (this.options.formState) {
        this.options.formState.isWildlife = isWildlife;
      }
    });
  }
  model: any = {};
  auctions: any[] = [];
  form = new FormGroup({});
  options: FormlyFormOptions = {
    formState: {
      isWildlife: true,
    },
  };
  fields: FormlyFieldConfig[] = [
    {
      fieldGroupClassName: 'space-y-5',
      fieldGroup: [
        {
          fieldGroupClassName: 'grid grid-cols-2 gap-3',
          fieldGroup: [
            {
              wrappers: ['key-value'],
              key: 'id',
              type: 'input',
              defaultValue: uuidv4(),
              props: {
                label: 'ID (AutoGenerated)',
                disabled: true,
              }
            },
            {
              wrappers: ['key-value'],
              key: 'auctionId',
              type: 'select',
              props: {
                label: 'Auction',
                required: true,
                filter: true,
                options: this.eventService.getAuctions(0, 500).pipe(
                  map(res => {
                    this.auctions = res.records.map(r => ({
                      label: r.nameOfAuction,
                      value: r.id,
                      date: r.dateOfAuction,
                      gpsCord1: r.gpsCord1,
                      gpsCord2: r.gpsCord2
                    }));

                    return this.auctions;
                  })
                ),
              },
              hooks: {
                onInit: (field) => {
                  field.formControl?.valueChanges.subscribe(id => {
                    if (id && this.auctions.length > 0) {
                      const auction = this.auctions.find(o => o.value === id);
                      if (auction) {
                        const date = auction.date ? moment(auction.date).format('DDMMMYY') : '';
                        this.model.name = `${date}${auction.label}`;
                        if (auction.gpsCord1 || auction.gpsCord2) {
                          const location = `${auction.gpsCord1 || ''}, ${auction.gpsCord2 || ''}`;
                          field.form?.get('location')?.patchValue(location);
                          this.model.location = location;
                        }
                      }
                    }
                  });
                }
              }
            },
            {
              wrappers: ['key-value'],
              key: 'location',
              type: 'lat-long',
              props: {
                label: 'Location',
                required: true,
              }
            },
            {
              wrappers: ['key-value'],
              key: 'type',
              type: 'select',
              defaultValue: 'Normal',
              props: {
                label: 'Type',
                options: [
                  {label: 'Normal', value: 'Normal'},
                  {label: 'Stud', value: 'Stud'}
                ],
              }
            },
            {
              wrappers: ['key-value'],
              key: 'status',
              type: 'select',
              defaultValue: 'Processing',
              props: {
                label: 'Status',
                options: [
                  {label: 'Finalized', value: 'Finalized'},
                  {label: 'Processing', value: 'Processing'}
                ],
              }
            },
            {
              wrappers: ['key-value'],
              key: 'depositAmount',
              type: 'number',
              defaultValue: 0,
              props: {
                label: 'Deposit Amount',
              }
            }
          ]
        },
        {
          wrappers: ['header'],
          fieldGroupClassName: 'grid grid-cols-2 gap-3',
          props: {
            headerLabel: 'Commissions'
          },
          fieldGroup: [
            {
              wrappers: ['header'],
              props: {
                headerLabel: 'Seller Commission',
                styleClass: 'bg-gray-100'
              },
              fieldGroupClassName: 'grid grid-cols-2 gap-3',
              fieldGroup: [
                {
                  key: 'sellerCommissionType',
                  type: 'toggle-input',
                  className: 'col-span-2',
                  defaultValue: false,
                  props: {
                    label: 'Seller Commission Type (Value/Percentage)',
                  }
                },
                {
                  key: 'seller',
                  type: 'number',
                  defaultValue: 0,
                  props: {
                    label: 'Seller Commission',
                    required: true,
                  },
                  expressions: {
                    'hide': 'formState.isWildlife'
                  },
                  hooks: {
                    onInit: (field) => {
                      field.formControl?.valueChanges.subscribe((value) => {
                        if (value && field.options && !this.isWildlife) {
                          const feeKeys = [
                            'sellerAuctionFee',
                            'sellerEventFee',
                            'sellerClubFee',
                            'sellerVeterinaryFee',
                            'sellerMarketingFee',
                          ];
                          const split = +(value / feeKeys.length).toFixed(2);
                          const patch: any = {};
                          feeKeys.forEach(k => patch[k] = split);
                          field.form?.patchValue(patch);
                        }
                      });
                    }
                  },
                },
                {
                  key: 'sellerAuctionFee',
                  type: 'number',
                  props: {
                    label: 'Auction Fees',
                    required: true,
                  },
                  expressions: {
                    'props.disabled': '!formState.isWildlife && !model.seller'
                  }
                },
                {
                  key: 'sellerEventFee',
                  type: 'number',
                  props: {
                    label: 'Event/Kraal/Boma Fees',
                    required: true,
                  },
                  expressions: {
                    'props.disabled': '!formState.isWildlife && !model.seller'
                  }
                },
                {
                  key: 'sellerClubFee',
                  type: 'number',
                  props: {
                    label: 'Club Fees',
                    required: true,
                  },
                  expressions: {
                    'props.disabled': '!formState.isWildlife && !model.seller'
                  }
                },
                {
                  key: 'sellerVeterinaryFee',
                  type: 'number',
                  props: {
                    label: 'Veterinary Fees',
                    required: true,
                  },
                  expressions: {
                    'props.disabled': '!formState.isWildlife && !model.seller'
                  }
                },
                {
                  key: 'sellerMarketingFee',
                  type: 'number',
                  props: {
                    label: 'Marketing Fees',
                    required: true,
                  },
                  expressions: {
                    'props.disabled': '!formState.isWildlife && !model.seller'
                  }
                }
              ]
            },
            {
              wrappers: ['header'],
              props: {
                headerLabel: 'Buyer Commission',
                styleClass: 'bg-gray-100'
              },
              expressions: {
                'hide': 'formState.isWildlife'
              },
              fieldGroupClassName: 'grid grid-cols-2 gap-3',
              fieldGroup: [
                {
                  key: 'buyerCommissionType',
                  type: 'toggle-input',
                  className: 'col-span-2',
                  defaultValue: false,
                  props: {
                    label: 'Buyer Commission Type (Value/Percentage)',
                  }
                },
                {
                  key: 'buyer',
                  type: 'number',
                  defaultValue: 0,
                  props: {
                    label: 'Buyer Commission',
                    required: true,
                  },
                  hooks: {
                    onInit: (field) => {
                      field.formControl?.valueChanges.subscribe((value) => {
                        if (value && field.options) {
                          const formState = field.options.formState;
                          const feeKeys = [
                            'buyerAuctionFee',
                            'buyerEventFee',
                            'buyerClubFee',
                            'buyerVeterinaryFee',
                            'buyerMarketingFee',
                          ];
                          const split = +(value / feeKeys.length).toFixed(2);
                          const patch: any = {};
                          feeKeys.forEach(k => patch[k] = split);
                          field.form?.patchValue(patch);
                        }
                      });
                    }
                  },
                },
                {
                  key: 'buyerAuctionFee',
                  type: 'number',
                  props: {
                    label: 'Auction Fees',
                    required: true,
                  },
                  expressions: {
                    'props.disabled': '!model.buyer'
                  }
                },
                {
                  key: 'buyerEventFee',
                  type: 'number',
                  props: {
                    label: 'Event/Kraal/Boma Fees',
                    required: true,
                  },
                  expressions: {
                    'props.disabled': '!model.buyer'
                  }
                },
                {
                  key: 'buyerClubFee',
                  type: 'number',
                  props: {
                    label: 'Club Fees',
                    required: true,
                  },
                  expressions: {
                    'props.disabled': '!model.buyer'
                  }
                },
                {
                  key: 'buyerVeterinaryFee',
                  type: 'number',
                  props: {
                    label: 'Veterinary Fees',
                    required: true,
                  },
                  expressions: {
                    'props.disabled': '!model.buyer'
                  }
                },
                {
                  key: 'buyerMarketingFee',
                  type: 'number',
                  props: {
                    label: 'Marketing Fees',
                    required: true,
                  },
                  expressions: {
                    'props.disabled': '!model.buyer'
                  }
                }
              ]
            }
          ]
        }
      ]
    }
  ];

  ngOnInit() {
    this.options.formState.isWildlife = this.categoryService.isWildlife();
  }

  get isWildlife() {
    return this.categoryService.isWildlife();
  }
}
