import {Component, effect, input, OnInit, output} from '@angular/core';
import {FormGroup, ReactiveFormsModule} from '@angular/forms';
import {FormlyFieldConfig, FormlyModule} from '@ngx-formly/core';
import moment from 'moment';
import { v4 as uuidv4 } from 'uuid';
import {AppButton} from '@shared/components/app-button/app-button';
import {KeyValue} from '@shared/interfaces/keyvalue';

@Component({
  selector: 'app-event-form',
  imports: [
    ReactiveFormsModule,
    FormlyModule,
    AppButton
  ],
  templateUrl: './event-form.html',
  styleUrl: './event-form.scss',
})
export class EventForm implements OnInit {
  data = input<{
    [key: string]: any;
  }>();
  isEdit = input<boolean>(false);
  onSubmit = output();

  constructor() {
    effect(() => {
      const model = this.data();
      if (model && model['date'] && typeof model['date'] === 'string') {
        this.model = {...model, date: new Date(model['date'])};
      } else {
        this.model = {...model};
      }
    });
  }
  model: any = {};
  form = new FormGroup({});
  fields: FormlyFieldConfig[] = [
    {
      fieldGroupClassName: 'space-y-5',
      fieldGroup: [
        {
          fieldGroupClassName: 'grid grid-cols-2 gap-3',
          fieldGroup: [
            {
              wrappers: ['key-value'],
              key: 'id',
              type: 'input',
              defaultValue: uuidv4(),
              props: {
                label: 'ID (AutoGenerated)',
                disabled: true,
              }
            },
            {
              wrappers: ['key-value'],
              key: 'name',
              type: 'input',
              props: {
                label: 'Name (Autogenerated)',
                disabled: true,
              },
              expressions: {
                'model.name': () => {
                  let value = '';
                  if (this.model.date) {
                    value = moment(this.model.date).format('DDMMMYY');
                  }
                  if (this.model.description) {
                    value += this.model.description;
                  }
                  return value;
                }
              }
            },
            {
              wrappers: ['key-value'],
              key: 'date',
              type: 'datepicker',
              defaultValue: new Date(),
              props: {
                label: 'Date',
                required: true,
              }
            },
            {
              wrappers: ['key-value'],
              key: 'description',
              type: 'input',
              defaultValue: 'Event',
              props: {
                label: 'Description',
                required: true,
              }
            },
            {
              wrappers: ['key-value'],
              key: 'location',
              type: 'lat-long',
              props: {
                label: 'Location',
                required: true,
              }
            },
            {
              wrappers: ['key-value'],
              key: 'type',
              type: 'select',
              defaultValue: 'Normal',
              props: {
                label: 'Type',
                options: [
                  {label: 'Normal', value: 'Normal'},
                  {label: 'Stud', value: 'Stud'}
                ],
              }
            },
            {
              wrappers: ['key-value'],
              key: 'status',
              type: 'select',
              defaultValue: 'Uploaded',
              props: {
                label: 'Status',
                options: [
                  {label: 'Finalized', value: 'Finalized'},
                  {label: 'Processing', value: 'Processing'},
                  {label: 'Uploaded', value: 'Uploaded'}
                ],
              }
            },
            {
              wrappers: ['key-value'],
              key: 'depositAmount',
              type: 'number',
              defaultValue: 0,
              props: {
                label: 'Deposit Amount',
              }
            }
          ]
        },
        {
          wrappers: ['header'],
          fieldGroupClassName: 'grid grid-cols-2 gap-3',
          props: {
            headerLabel: 'Commissions'
          },
          options: {
            formState: {
              sellerFeesInitialized: false,
              buyerFeesInitialized: false
            }
          },
          fieldGroup: [
            {
              wrappers: ['header'],
              props: {
                headerLabel: 'Seller Commission',
                styleClass: 'bg-gray-100'
              },
              fieldGroupClassName: 'grid grid-cols-2 gap-3',
              fieldGroup: [
                {
                  key: 'sellerCommissionType',
                  type: 'toggle-input',
                  className: 'col-span-2',
                  defaultValue: false,
                  props: {
                    label: 'Seller Commission Type (Value/Percentage)',
                  }
                },
                {
                  key: 'seller',
                  type: 'number',
                  defaultValue: 0,
                  props: {
                    label: 'Seller Commission',
                    required: true,
                  },
                  hooks: {
                    onInit: (field) => {
                      field.formControl?.valueChanges.subscribe((value) => {
                        if (value && field.options) {
                          const feeKeys = [
                            'sellerAuctionFee',
                            'sellerEventFee',
                            'sellerClubFee',
                            'sellerVeterinaryFee',
                            'sellerMarketingFee',
                          ];
                          const split = +(value / feeKeys.length).toFixed(2);
                          const patch: any = {};
                          feeKeys.forEach(k => patch[k] = split);
                          field.form?.patchValue(patch);
                        }
                      });
                    }
                  },
                },
                {
                  key: 'sellerAuctionFee',
                  type: 'number',
                  props: {
                    label: 'Auction Fees',
                    required: true,
                  },
                  expressions: {
                    'props.disabled': () => {
                      return !this.model.seller;
                    }
                  }
                },
                {
                  key: 'sellerEventFee',
                  type: 'number',
                  props: {
                    label: 'Event/Kraal/Boma Fees',
                    required: true,
                  },
                  expressions: {
                    'props.disabled': () => {
                      return !this.model.seller;
                    }
                  }
                },
                {
                  key: 'sellerClubFee',
                  type: 'number',
                  props: {
                    label: 'Club Fees',
                    required: true,
                  },
                  expressions: {
                    'props.disabled': () => {
                      return !this.model.seller;
                    }
                  }
                },
                {
                  key: 'sellerVeterinaryFee',
                  type: 'number',
                  props: {
                    label: 'Veterinary Fees',
                    required: true,
                  },
                  expressions: {
                    'props.disabled': () => {
                      return !this.model.seller;
                    }
                  }
                },
                {
                  key: 'sellerMarketingFee',
                  type: 'number',
                  props: {
                    label: 'Marketing Fees',
                    required: true,
                  },
                  expressions: {
                    'props.disabled': () => {
                      return !this.model.seller;
                    }
                  }
                }
              ]
            },
            {
              wrappers: ['header'],
              props: {
                headerLabel: 'Buyer Commission',
                styleClass: 'bg-gray-100'
              },
              fieldGroupClassName: 'grid grid-cols-2 gap-3',
              fieldGroup: [
                {
                  key: 'buyerCommissionType',
                  type: 'toggle-input',
                  className: 'col-span-2',
                  defaultValue: false,
                  props: {
                    label: 'Buyer Commission Type (Value/Percentage)',
                  }
                },
                {
                  key: 'buyer',
                  type: 'number',
                  defaultValue: 0,
                  props: {
                    label: 'Buyer Commission',
                    required: true,
                  },
                  hooks: {
                    onInit: (field) => {
                      field.formControl?.valueChanges.subscribe((value) => {
                        if (value && field.options) {
                          const formState = field.options.formState;
                          const feeKeys = [
                            'buyerAuctionFee',
                            'buyerEventFee',
                            'buyerClubFee',
                            'buyerVeterinaryFee',
                            'buyerMarketingFee',
                          ];
                          const split = +(value / feeKeys.length).toFixed(2);
                          const patch: any = {};
                          feeKeys.forEach(k => patch[k] = split);
                          field.form?.patchValue(patch);
                        }
                      });
                    }
                  },
                },
                {
                  key: 'buyerAuctionFee',
                  type: 'number',
                  props: {
                    label: 'Auction Fees',
                    required: true,
                  },
                  expressions: {
                    'props.disabled': () => {
                      return !this.model.buyer;
                    }
                  }
                },
                {
                  key: 'buyerEventFee',
                  type: 'number',
                  props: {
                    label: 'Event/Kraal/Boma Fees',
                    required: true,
                  },
                  expressions: {
                    'props.disabled': () => {
                      return !this.model.buyer;
                    }
                  }
                },
                {
                  key: 'buyerClubFee',
                  type: 'number',
                  props: {
                    label: 'Club Fees',
                    required: true,
                  },
                  expressions: {
                    'props.disabled': () => {
                      return !this.model.buyer;
                    }
                  }
                },
                {
                  key: 'buyerVeterinaryFee',
                  type: 'number',
                  props: {
                    label: 'Veterinary Fees',
                    required: true,
                  },
                  expressions: {
                    'props.disabled': () => {
                      return !this.model.buyer;
                    }
                  }
                },
                {
                  key: 'buyerMarketingFee',
                  type: 'number',
                  props: {
                    label: 'Marketing Fees',
                    required: true,
                  },
                  expressions: {
                    'props.disabled': () => {
                      return !this.model.buyer;
                    }
                  }
                }
              ]
            }
          ]
        }
      ]
    }
  ];

  ngOnInit() {}
}
